version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cookbook_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1662
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cookbook_network
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1662@db:5432/cookbook_db
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=5242880
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - db
    networks:
      - cookbook_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend (Production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:8000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cookbook_network
    restart: unless-stopped

volumes:
  postgres_data:
  backend_uploads:

networks:
  cookbook_network:
    driver: bridge
