version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cookbook_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1662
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cookbook_network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1662@db:5432/cookbook_db
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=5242880
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    depends_on:
      - db
    networks:
      - cookbook_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - cookbook_network
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data:
  backend_uploads:

networks:
  cookbook_network:
    driver: bridge

